insert into moedas (id_moeda,moeda,operacao) values(1, 'Dolar','V');
insert into moedas (id_moeda,moeda,operacao) values (10813, 'Dolar','C');
insert into moedas (id_moeda,moeda,operacao) values(21619, 'Euro','V');
insert into moedas (id_moeda,moeda,operacao) values(21620,'Euro','C');
insert into moedas (id_moeda,moeda,operacao) values(21621, 'Iene','V');
insert into moedas (id_moeda,moeda,operacao) values(21622, 'Iene','C');
insert into moedas (id_moeda,moeda,operacao) values(21623, 'Libra esterlina','V');
insert into moedas (id_moeda,moeda,operacao) values(21624, 'Libra esterlina','C');
insert into moedas (id_moeda,moeda,operacao) values(21625, 'Franco Suíço','V');
insert into moedas (id_moeda,moeda,operacao) values(21626, 'Franco Suíço','C');
insert into moedas (id_moeda,moeda,operacao) values(21627, 'Coroa Dinamarquesa','V');
insert into moedas (id_moeda,moeda,operacao) values(21628, 'Coroa Dinamarquesa','C');
insert into moedas (id_moeda,moeda,operacao) values(21629, 'Coroa Norueguesa','V');
insert into moedas (id_moeda,moeda,operacao) values(21630, 'Coroa Norueguesa','C');
insert into moedas (id_moeda,moeda,operacao) values(21631, 'Coroa Sueca','V');
insert into moedas (id_moeda,moeda,operacao) values(21632, 'Coroa Sueca','C');
insert into moedas (id_moeda,moeda,operacao) values(21633, 'Dolar Australiano','V');
insert into moedas (id_moeda,moeda,operacao) values(21634, 'Dolar Australiano','C');
insert into moedas (id_moeda,moeda,operacao) values(21635, 'Dolar Canadense','V');
insert into moedas (id_moeda,moeda,operacao) values(21636, 'Dolar Canadense','C');